name: Calibrate Processing

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'folder_name input for the calibrateprocessing.py script'
        required: true
        default: ""

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r processing_requirements.txt

    - name: Run calibrateprocessing.py
      run: |
        python calibrateprocessing.py ${{ github.event.inputs.input_value }}

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "github-actions@example.com"

    - name: Commit and push new file
      run: |
        git add ${{ github.event.inputs.input_value }}/DataAvg.txt
        git commit -m "Add ${{ github.event.inputs.input_value }}/DataAvg.txt generated by calibrateprocessing.py"
        git push






